# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
    spec:
      containers:
      - name: eshop-frontend
        image: gcr.io/ecommerce-nag/eshop-frontend:latest
        ports:
        - containerPort: 80

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-fe-service
spec:
  selector:
    app: eshop-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 34.28.131.230
